version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: veera_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: veeratube
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: veera_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: veera_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
